POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "Development with WebStorm",
  "author": "Panu Valtanen",
  "url": "google.com",
  "likes": 50,
  "userId": "5f71be90fb280c4c1cedffbc"
}

###
